# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_pgdraw <- function(b, c) {
    .Call('_binnetskeleton_rcpp_pgdraw', PACKAGE = 'binnetskeleton', b, c)
}

gibbs_hierarchical_samples <- function(number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress) {
    .Call('_binnetskeleton_gibbs_hierarchical_samples', PACKAGE = 'binnetskeleton', number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress)
}

gibbs_hierarchical_eap <- function(number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress) {
    .Call('_binnetskeleton_gibbs_hierarchical_eap', PACKAGE = 'binnetskeleton', number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress)
}

gibbs_uniform_samples <- function(number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress) {
    .Call('_binnetskeleton_gibbs_uniform_samples', PACKAGE = 'binnetskeleton', number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress)
}

gibbs_uniform_eap <- function(number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress) {
    .Call('_binnetskeleton_gibbs_uniform_eap', PACKAGE = 'binnetskeleton', number_burnin_iterations, number_iterations, x, sigma, gamma, spike_var, slab_var, include, sufC, alpha, beta, number_edges, theta, prior_var_intercepts, df, components, display_progress)
}

